module.exports.USERSCOPESLOCATION = {
    DEFAULT: "DEFAULT"
}

module.exports.LOGICALSTRATEGY = {
    AND: "AND",
    OR: "OR",
}

module.exports.FLOWSTRATEGY = {
    RETURNRESPONSE: "RETURNRESPONSE",
    NEXTWITHERROR: "NEXTWITHERROR",
}